### ISSUE TITLE
MATCHSTICK_VERSION in Dockerfile

### ISSUE THREAD

**Issue by GMSteuart** [LimeChain/demo-subgraph#23]
https://github.com/LimeChain/demo-subgraph/blob/69c8d0816ca60da27f95adc49fe3c3e5b68c7782/Dockerfile#L15

This line is really close to allowing `MATCHSTICK_VERSION` as an env var. The Dockerfile in it's current state isn't plug-n-play as the copy and paste directions would imply. Many other small optimizations can be done to the Dockerfile too (e.g. minimize number of layers)

**Comment by dimitrovmaksim** [comment]
This is a placeholder for the version. I think from graph-cli 0.25.3 and upwards, you can run matchstick with docker by executing `graph test -d` (run `graph test -h` for more info). The instructions [here](https://github.com/LimeChain/matchstick#docker-) are before docker was available through graph-cli. Other than that if you have any specific suggestion how to improve it, you can either share them with us here or open a PR

**Comment by GMSteuart** [comment]
I would make the following changes to the Dockerfile:
- Add MATCHSTICK_VERSION as an env var and set the default value to the latest version
- Merge the first set of RUN statements into one to reduce layers
- Use the node alpine image to reduce the overall size
- Remove the ARGS env var and use ENTRYPOINT to utilize docker's built in behavior on passing arguments
